# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ICMPC 14 Schedule
email: gabe@psych.ryerson.ca
description: > # this means to ignore newlines until "baseurl:"
  A chronological organization of the ICMPC14 talk schedule.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gabenespoli.github.io" # the base hostname & protocol for your site
twitter_username: gabenespoli
github_username:  gabenespoli

# Build settings
markdown: kramdown
